export const StackNav = {
  splash: 'splash',
  OnBoarding: 'OnBoarding',
  AuthNavigation: 'AuthNavigation',
  TabNavigation: 'TabNavigation',
  TransferMoney: 'TransferMoney',
  SendMoney: 'SendMoney',
  TransferProof: 'TransferProof',
  TopUpScreen: 'TopUpScreen',
  FechamentoCaixaScreen: 'FechamentoCaixaScreen',
  ConfiguracoesCaixaScreen: 'ConfiguracoesCaixaScreen',
  SacarCaixaScreen: 'SacarCaixaScreen',
  DepositarCaixaScreen: 'DepositarCaixaScreen',
  Confirmation: 'Confirmation',
  WithDrawBalance: 'WithDrawBalance',
  HistoryTrans: 'HistoryTrans',
  HistoryDetails: 'HistoryDetails',
  SeeMyCard: 'SeeMyCard',
  EditCard: 'EditCard',
  AccountInfo: 'AccountInfo',
  EditAccount: 'EditAccount',
  SelectLanguage: 'SelectLanguage',
  GeneralSetting: 'GeneralSetting',
  ReferralCode: 'ReferralCode',
  ContactsList: 'ContactsList',
  Notification: 'Notification',
  FQA: 'FQA',
  ActivityGraph: 'ActivityGraph',
  MoreOptions: 'MoreOptions',
  ChatScreen: 'CHatScreen',
  ATMDetails: 'ATMDetails',
  SelectProvider: 'SelectProvider',
  TopUpModal: 'TopUpModal',
  PhoneBook: 'PhoneBook',
  LogOut: 'LogOut',
  AlterarEmpresa: 'AlterarEmpresa'
};

export const AuthNav = {
  SignIn: 'SignIn',
  PassRecovery: 'PassRecovery',
  OtpAuth: 'OtpAuth',
  VerifyIdentity: 'VerifyIdentity',
  CreatePass: 'CreatePass',
  SignUp: 'SignUp',
  CountryRes: 'CountryRes',
  Reasons: 'Reasons',
  CreatePin: 'CreatePin',
  FaceIdentity: 'faceIdentity',
  ProofRes: 'ProofRes',
  CardOnBoarding: 'CardOnBoarding',
  CardStyle: 'CardStyle',
  NewCard: 'NewCard',
};

export const TabNav = {
  HomeScreen: 'HomeScreen',
  MyCardScreen: 'MyCardScreen',
  ActivityScreen: 'ActivityScreen',
  ProfileScreen: 'ProfileScreen'
};